
try{
    console.log("Test is try area");
}
catch(err){
    
}